site_name: accesslabsproxy
pages:
- [index.md, Home]
- [about.md, About]
- [installation.md, Installation]
- [usage.md, Usage]
theme: readthedocs
repo_url: https://github.com/redhataccess/accesslabsproxy/
